### ISSUE TITLE
A simple example and explanation of the syntax would go a long way

### ISSUE THREAD

**Issue by hlindberg** [kuba--/ut#4]
Thanks for making this package available. I will be using this package for unification in a project of mine. At first, I did not understand the syntax of the input to `Unify`, but it became apparent when I followed the references to whitepapers. Adding the following to the README would have saved me some time. Hopefully, it will be of benefit to the next person interested in unification.

Unification unifies terms. A term is one of variable, constant, functor, or literal value. A variable starts with an upper case letter and their names are the keys in the map returned by `Unify`. Constants start with a lowercase letter. Values are integers, floating point values, or strings. As a simple example:
```
x,y := `f(X,Y)`, `f(1,"hello")`
```
This would unify the functor `f` such that the variable X is `1` and the variable `Y` is `"hello"` in the returned map.

**Comment by kuba--** [comment]
Thanks, done!
